name: Deploy Jekyll site

on:
  push:
    branches:
      - main # 또는 너의 기본 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Install Dependencies
        run: |
          bundle install
          gem install jekyll-remote-theme  # 필수!

      - name: Build Site
        run: JEKYLL_ENV=production bundle exec jekyll build
